//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plato_Pedido
    {
        public int PlatoPedidoId { get; set; }
        public int PlatoId { get; set; }
        public int PedidoId { get; set; }
        public string Cantidad { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Plato Plato { get; set; }
    }
}
